running test
running egg_info
writing requirements to libauthkit.egg-info/requires.txt
writing libauthkit.egg-info/PKG-INFO
writing top-level names to libauthkit.egg-info/top_level.txt
writing dependency_links to libauthkit.egg-info/dependency_links.txt
writing entry points to libauthkit.egg-info/entry_points.txt
writing requirements to libauthkit.egg-info/requires.txt
writing libauthkit.egg-info/PKG-INFO
writing top-level names to libauthkit.egg-info/top_level.txt
writing dependency_links to libauthkit.egg-info/dependency_links.txt
writing entry points to libauthkit.egg-info/entry_points.txt
reading manifest file 'libauthkit.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'libauthkit.egg-info/SOURCES.txt'
running build_ext
Failure: ImportError (cannot import name status_checker) ... ERROR
Failure: TypeError (__init__() takes exactly 2 arguments (1 given)) ... ERROR
Failure: NameError (name 'paste' is not defined) ... ERROR
test_multihandler.test_ok ... FAIL
test_multihandler.test_intercept ... FAIL
test_multihandler.test_fail ... FAIL
test_multihandler.test_form_fail ... FAIL
test_multihandler.test_forward_fail ... FAIL
test_multihandler.test_redirect_fail ... FAIL
test_sqlalchemy.test_users_api_database ... ERROR
test_sqlalchemy.test_users_model_api_database ... ERROR

======================================================================
ERROR: Failure: ImportError (cannot import name status_checker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/loader.py", line 382, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/steiner/src/notmm/branches/0.4-stable/extras/libauthkit/authkit/middleware/__init__.py", line 16, in <module>
    from multi import MultiHandler, status_checker
ImportError: cannot import name status_checker

======================================================================
ERROR: Failure: TypeError (__init__() takes exactly 2 arguments (1 given))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/loader.py", line 382, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/steiner/src/notmm/branches/0.4-stable/extras/libauthkit/authkit/users/schevo_driver/__init__.py", line 1, in <module>
    from model import db
  File "/home/steiner/src/notmm/branches/0.4-stable/extras/libauthkit/authkit/users/schevo_driver/model.py", line 9, in <module>
    db = XdserverProxy(dbName='accounts')
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: Failure: NameError (name 'paste' is not defined)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/loader.py", line 382, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/steiner/src/notmm/branches/0.4-stable/extras/libauthkit/test/test_base.py", line 25, in <module>
    form_app = paste.lint.middleware(form_app)
NameError: name 'paste' is not defined

======================================================================
ERROR: test_sqlalchemy.test_users_api_database
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/home/steiner/src/notmm/branches/0.4-stable/extras/libauthkit/test/test_sqlalchemy.py", line 58, in test_users_api_database
    raise Exception("Could not run the SQLAlchemy tests, SQLAlchemyManager is not installed")
Exception: Could not run the SQLAlchemy tests, SQLAlchemyManager is not installed

======================================================================
ERROR: test_sqlalchemy.test_users_model_api_database
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/home/steiner/src/notmm/branches/0.4-stable/extras/libauthkit/test/test_sqlalchemy.py", line 362, in test_users_model_api_database
    import model as test_model
  File "/home/steiner/src/notmm/branches/0.4-stable/extras/libauthkit/examples/user/database-model/model.py", line 1, in <module>
    from notmm.utils.sql.session import ScopedSession
ImportError: No module named sql.session

======================================================================
FAIL: test_multihandler.test_ok
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/home/steiner/src/notmm/branches/0.4-stable/extras/libauthkit/test/test_multihandler.py", line 65, in test_ok
    res = TestApp(app).get('')
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/fixture.py", line 208, in get
    return self.do_request(req, status=status)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/fixture.py", line 389, in do_request
    **req.environ)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/wsgilib.py", line 343, in raw_interactive
    app_iter = application(basic_environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/lint.py", line 170, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/lint.py", line 172, in lint_app
    "The application must return an iterator, if only an empty list")
AssertionError: The application must return an iterator, if only an empty list
-------------------- >> begin captured logging << --------------------
authkit.authenticate.cookie: DEBUG: These cookies were found: []
authkit.authenticate.cookie: DEBUG: Our cookie 'authkit' value is therefore ''
authkit.authenticate.cookie: DEBUG: Remote addr '0.0.0.0', value '', include_ip True
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_multihandler.test_intercept
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/home/steiner/src/notmm/branches/0.4-stable/extras/libauthkit/test/test_multihandler.py", line 117, in test_intercept
    assertEqual(res.full_status, '401 Unauth')
  File "/home/steiner/src/notmm/branches/0.4-stable/extras/libauthkit/test/test_multihandler.py", line 37, in assertEqual
    raise AssertionError('%s != %s'%(a,b))
AssertionError: 401 Unauthorized != 401 Unauth
-------------------- >> begin captured logging << --------------------
authkit.authenticate.multi: DEBUG: Status: '403 Forbidden', Headers: [('Content-type', 'text/plain; charset=utf8')]
authkit.authenticate.multi: DEBUG: Status checker received status '403 Forbidden', headers [('Content-type', 'text/plain; charset=utf8')], intercepted ['401', '403', '702']
authkit.authenticate.multi: DEBUG: Status checker returns True
authkit.authenticate.multi: DEBUG: MultiMiddleware self.checker check() returning <authkit.authenticate.digest.DigestAuthHandler object at 0x9e71f0c>
authkit.authenticate.multi: DEBUG: Matched binding returns status: '401 Unauthorized', headers: [('WWW-Authenticate', 'Digest nonce="efbf1a717bc3e78b97a6d9f15f66fc22", opaque="cd3eb01f48f867e9438391535427fa5c", realm="test", qop="auth"'), ('content-type', 'text/plain; charset=utf8')], exc_info: None
authkit.authenticate.multi: DEBUG: Status: '702 Doesnt exist', Headers: [('Content-type', 'text/plain; charset=utf8')]
authkit.authenticate.multi: DEBUG: Status checker received status '702 Doesnt exist', headers [('Content-type', 'text/plain; charset=utf8')], intercepted ['401', '403', '702']
authkit.authenticate.multi: DEBUG: Status checker returns True
authkit.authenticate.multi: DEBUG: MultiMiddleware self.checker check() returning <authkit.authenticate.digest.DigestAuthHandler object at 0x9e71f0c>
authkit.authenticate.multi: DEBUG: Matched binding returns status: '401 Unauthorized', headers: [('WWW-Authenticate', 'Digest nonce="4cb14d84fb125fedca5bc165116e4cfa", opaque="fcefee799ea8ac7206258c59769c1e91", realm="test", qop="auth"'), ('content-type', 'text/plain; charset=utf8')], exc_info: None
authkit.authenticate.multi: DEBUG: Status: '500 Error', Headers: [('Content-type', 'text/plain; charset=utf8')]
authkit.authenticate.multi: DEBUG: Status checker received status '500 Error', headers [('Content-type', 'text/plain; charset=utf8')], intercepted ['401', '403', '702']
authkit.authenticate.multi: DEBUG: Status checker returns False
authkit.authenticate.multi: DEBUG: Multi: No binding was found for the check
authkit.authenticate.multi: DEBUG: Status: '401 Unauthorized', Headers: [('Content-type', 'text/plain; charset=utf8')]
authkit.authenticate.multi: DEBUG: Status checker received status '401 Unauthorized', headers [('Content-type', 'text/plain; charset=utf8')], intercepted ['401', '403', '702']
authkit.authenticate.multi: DEBUG: Status checker returns True
authkit.authenticate.multi: DEBUG: MultiMiddleware self.checker check() returning <authkit.authenticate.digest.DigestAuthHandler object at 0x9e71f0c>
authkit.authenticate.multi: DEBUG: Matched binding returns status: '401 Unauthorized', headers: [('WWW-Authenticate', 'Digest nonce="7b4d5e452688f42896c6268bbb68116f", opaque="847f5d5678340382d220108f4be2a234", realm="test", qop="auth"'), ('content-type', 'text/plain; charset=utf8')], exc_info: None
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_multihandler.test_fail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/home/steiner/src/notmm/branches/0.4-stable/extras/libauthkit/test/test_multihandler.py", line 122, in test_fail
    res = TestApp(app).get('/private', status=401)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/fixture.py", line 208, in get
    return self.do_request(req, status=status)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/fixture.py", line 389, in do_request
    **req.environ)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/wsgilib.py", line 343, in raw_interactive
    app_iter = application(basic_environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/lint.py", line 170, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/lint.py", line 172, in lint_app
    "The application must return an iterator, if only an empty list")
AssertionError: The application must return an iterator, if only an empty list

======================================================================
FAIL: test_multihandler.test_form_fail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/home/steiner/src/notmm/branches/0.4-stable/extras/libauthkit/test/test_multihandler.py", line 130, in test_form_fail
    res = TestApp(form_app).get('/private', status=200)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/fixture.py", line 208, in get
    return self.do_request(req, status=status)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/fixture.py", line 389, in do_request
    **req.environ)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/wsgilib.py", line 343, in raw_interactive
    app_iter = application(basic_environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/lint.py", line 170, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/lint.py", line 172, in lint_app
    "The application must return an iterator, if only an empty list")
AssertionError: The application must return an iterator, if only an empty list
-------------------- >> begin captured logging << --------------------
authkit.authenticate.cookie: DEBUG: These cookies were found: []
authkit.authenticate.cookie: DEBUG: Our cookie 'authkit' value is therefore ''
authkit.authenticate.cookie: DEBUG: Remote addr '0.0.0.0', value '', include_ip True
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_multihandler.test_forward_fail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/home/steiner/src/notmm/branches/0.4-stable/extras/libauthkit/test/test_multihandler.py", line 137, in test_forward_fail
    assertEqual(res.header('content-type'),'text/plain; charset=utf8')
  File "/home/steiner/src/notmm/branches/0.4-stable/extras/libauthkit/test/test_multihandler.py", line 37, in assertEqual
    raise AssertionError('%s != %s'%(a,b))
AssertionError: text/html != text/plain; charset=utf8
-------------------- >> begin captured logging << --------------------
authkit.authenticate.cookie: DEBUG: These cookies were found: []
authkit.authenticate.cookie: DEBUG: Our cookie 'authkit' value is therefore ''
authkit.authenticate.cookie: DEBUG: Remote addr '0.0.0.0', value '', include_ip True
authkit.authenticate.multi: DEBUG: Status: '401 Not signed in', Headers: []
authkit.authenticate.multi: DEBUG: Status checker received status '401 Not signed in', headers [], intercepted ['401']
authkit.authenticate.multi: DEBUG: Status checker returns True
authkit.authenticate.multi: DEBUG: MultiMiddleware self.checker check() returning <authkit.authenticate.forward.Redirect object at 0x9dc2bec>
authkit.authenticate.multi: DEBUG: Status: '200 Sign in required', Headers: [('Content-type', 'text/html')]
authkit.authenticate.multi: DEBUG: Status checker received status '200 Sign in required', headers [('Content-type', 'text/html')], intercepted ['401']
authkit.authenticate.multi: DEBUG: Status checker returns False
authkit.authenticate.multi: DEBUG: Multi: No binding was found for the check
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_multihandler.test_redirect_fail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/home/steiner/src/notmm/branches/0.4-stable/extras/libauthkit/test/test_multihandler.py", line 150, in test_redirect_fail
    res = TestApp(redirect_app).get('/private', status=302)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/fixture.py", line 208, in get
    return self.do_request(req, status=status)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/fixture.py", line 389, in do_request
    **req.environ)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/wsgilib.py", line 343, in raw_interactive
    app_iter = application(basic_environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/lint.py", line 170, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/usr/local/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/lint.py", line 172, in lint_app
    "The application must return an iterator, if only an empty list")
AssertionError: The application must return an iterator, if only an empty list
-------------------- >> begin captured logging << --------------------
authkit.authenticate.cookie: DEBUG: These cookies were found: []
authkit.authenticate.cookie: DEBUG: Our cookie 'authkit' value is therefore ''
authkit.authenticate.cookie: DEBUG: Remote addr '0.0.0.0', value '', include_ip True
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 11 tests in 0.687s

FAILED (failures=6, errors=5)
